name: Trigger auto deployment for myelasticsearch

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/myelasticsearch-AutoDeployTrigger-05c67981-f813-4b10-a2d4-671a23385378.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mytestdemo.azurecr.io
          username: ${{ secrets.MYELASTICSEARCH_REGISTRY_USERNAME }}
          password: ${{ secrets.MYELASTICSEARCH_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mytestdemo.azurecr.io/systan:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYELASTICSEARCH_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myelasticsearch -g incident --server mytestdemo.azurecr.io --username  ${{ secrets.MYELASTICSEARCH_REGISTRY_USERNAME }} --password ${{ secrets.MYELASTICSEARCH_REGISTRY_PASSWORD }}
            az containerapp update -n myelasticsearch -g incident --image mytestdemo.azurecr.io/systan:${{ github.sha }}
